name: housekeeping

on:
  push:
    branches-ignore:    
      - 'main'
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.6

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with: 
          version: 1.6.1
          virtualenvs-create: false

      - name: Install dependencies
        run: poetry install

      - name: Check linting
        run: ruff check

      - name: Check formatting
        run: ruff format --check

      - name: Build python SDK package
        if: github.event.pull_request.merged == true
        run: poetry build
